config/routes.rb
Oldtape::Application.routes.draw do
  #get "build_mixtape/create/:mid/:sid/:order" => 'build_mixtape#create'
  #get "build_mixtape/destroy"

  # Automatic routes generated by Devise
  devise_for :users

  # Default route
  root :to => 'artists#index'

  # Resourceful Routes
  resources :artists, :albums, :songs, :mixtapes, :build_mixtape

	# Nested Resourceful Routes
	# resources :artists do
	#   resources :albums
	# end

	# We can define additional routes for albums except nested resources above like this.
	# resources :albums
  # get '/albums/:id' => 'albums#show'
end

app/models/album.rb
class Album
  include Mongoid::Document

  field :name, type: String
  field :info, type: String
  field :release_date, type: Integer

  belongs_to :artist
  has_many   :songs
end

app/models/artist.rb
class Artist
  include Mongoid::Document

  field :name, type: String
  field :bio, type: String
  field :start_date, type: Integer
  field :end_date, type: Integer

  has_many :albums
end

app/models/clementine.rb
class Clementine < ActiveRecord::Base
  self.establish_connection(
    {  :adapter => 'sqlite3',
	   :database => 'db/clementine.db',
	   :pool => 5,
	   :timeout => 5000
	}
 )
end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
  attr_accessible :description, :image, :name

  has_many :mixtape_songs
  has_many :songs, :through => :mixtape_songs
end

app/models/mixtape_song.rb
class MixtapeSong < ActiveRecord::Base
  attr_accessible :mixtape_id, :order, :song_id

  belongs_to :mixtape
  belongs_to :song
end

app/models/song.rb
class Song
  include Mongoid::Document

  field :name, type: String
  field :track, type: Integer
  field :duration, type: String

  belongs_to :album

  # Fix it later for mongodb
  #has_many :mixtape_songs
  #has_many :mixtapes, :through => :mixtape_songs

  # Fix it later for mongodb
  #include Tire::Model::Search
  #include Tire::Model::Callbacks

  # old basic seach method
  #def self.search(search)
  #  if search.blank?
  #    nil
  #  else
  #    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  #  end
  #end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :trackable
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, :default => 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  ## Token authenticatable
  # field :authentication_token, type: String

  # run 'rake db:mongoid:create_indexes' to create indexes
  index({email: 1}, {unique: true})

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
  end

  def index
  end

  def new
	if params[:artist_id].blank?
		redirect_to artists_path
	else
		@album = Album.new
	end
  end

  def create
  	@album = Album.new(params[:album])

    if @album.save
      redirect_to @album, :notice => 'Album was successfully created.'
    else
      render :action => "new"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!

  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
  	@artist = Artist.new(params[:artist])

    if @artist.save
      redirect_to(@artist, :notice => 'Artist was successfully created.')
    else
      render :action => "new"
    end
  end
end

app/controllers/build_mixtape_controller.rb
class BuildMixtapeController < ApplicationController
  def create
    vals = {:mixtape_id => params[:mid], :song_id => params[:sid], :order => params[:order]}
    @mixtape_song = MixtapeSong.new(vals)

    if @mixtape_song.save
      redirect_to mixtape_path(@mixtape_song.mixtape_id), :notice => 'Song added to mixtape'
    else
      redirect_to mixtape_path(@mixtape_song.mixtape_id), :notice => 'Process failed!'
    end
  end

  def destroy
    @mixtape_song = MixtapeSong.find(params[:id])
    @mixtape_song.destroy
    flash[:notice] = "Song removed."
    redirect_to mixtapes_path
  end
end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  before_filter :find_mixtape, :only => [:show, :edit, :update, :destroy]

  def index
    @mixtapes = Mixtape.all
  end

  def show
	if params[:query].present?
      @songs = Song.search(params[:query], load: true)
    else
      @songs = nil
    end
  end

  def create
    @mixtape = Mixtape.new(params[:mixtape])

    if @mixtape.save
      redirect_to @mixtape, notice: 'Your mixtape was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @mixtape.update_attributes(params[:mixtape])
      redirect_to @mixtape, :notice => 'Your mixtape was succesfully updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @mixtape.destroy
    redirect_to mixtapes_path
  end

  def new
    @mixtape = Mixtape.new
  end

  protected
    def find_mixtape
      @mixtape = Mixtape.find(params[:id])
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
    @song = Song.find(params[:id])
  end

  def index
  end

  def new
	if params[:album_id].blank?
		redirect_to artists_path
	else
		@song = Song.new
	end
  end

  def create
  	@song = Song.new(params[:song])

    if @song.save
      redirect_to album_path(@song.album_id), :notice => 'Song was successfully created.'
    else
      render :action => "new"
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/build_mixtape_helper.rb
module BuildMixtapeHelper
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @album.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@album.errors.count, 'error') %> prohibited
        this album from being saved:</h2>
    <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.hidden_field :artist_id, :value => params[:artist_id] %>
 
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :info, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :info, :size => '10x5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :release_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :release_date %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
    <%= link_to 'Back', artist_path(params[:artist_id]), :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/albums/new.html.erb
<div class="page-header">
  <h1>New Album</h1>
</div>
 
<%= render 'form' %>

app/views/albums/show.html.erb
<div class="page-header">
  <h1>
    <%= @album.name %>
    <small>[<%= @album.release_date %>]</small>
  </h1>
</div>

<p class="lead">
  <%= @album.info %>
</p>

<h6>Songs</h6>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Track</th>
    <th>Name</th>
    <th>Duration</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @album.songs.each do |song| %>
      <tr>
        <td><%= song.track %></td>
        <td><%= song.name %></td>
        <td><%= song.duration %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Song', new_song_path(:album_id => @album.id), :class => 'btn btn-primary' %>

app/views/artists/_form.html.erb
<%= form_for(@artist, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @artist.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@artist.errors.count, 'error') %> prohibited
        this artist from being saved:</h2>
    <ul>
    <% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
      <p class="help-block">Supporting help text</p>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :bio, :size => '10x5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :start_date %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :end_date %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Create", :class => 'btn btn-primary' %>
    <%= link_to "Cancel", artists_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/artists/index.html.erb
<div class="page-header">
  <h1>Artists</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @artists.each do |artist| %>
    <tr>
      <td style="width: 150px;"><%= link_to artist.name, artist %></td>
      <td><%= artist.bio.length > 125 ? "#{artist.bio[0,125]}..." : artist.bio %></td>
      <td style="width: 100px;"><%= artist.start_date %> - <%= artist.end_date.blank? ? 'present' : artist.end_date %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Artist', new_artist_path, :class => 'btn btn-primary' %>

app/views/artists/new.html.erb
<div class="page-header">
  <h1>New artist</h1>
</div>
 
<%= render 'form' %>

app/views/artists/show.html.erb
<div class="page-header">
  <h1>
    <%= @artist.name %>
    <small>[<%= @artist.start_date %> - <%= @artist.end_date.blank? ? 'present' : @artist.end_date %>]</small>
  </h1>
</div>

<p class="lead">
  <%= @artist.bio %>
</p>

<h6>Albums</h6>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Info</th>
    <th>Release</th>
  </tr>
  </thead>

  <tbody>
  <% @artist.albums.each do |album| %>
      <tr>
        <td style="width:200px;"><%= link_to album.name, album %></td>
        <td><%= album.info.length > 100 ? "#{album.info[0,100]}..." : album.info %></td>
        <td><%= album.release_date %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Album', new_album_path(:artist_id => @artist.id), :class => 'btn btn-primary' %>

app/views/build_mixtape/create.html.erb
<h1>BuildMixtape#create</h1>
<p>Find me in app/views/build_mixtape/create.html.erb</p>

app/views/build_mixtape/destroy.html.erb
<h1>BuildMixtape#destroy</h1>
<p>Find me in app/views/build_mixtape/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oldtape</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Oldtape</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Create One!", artists_path %></li>
          <li><%= link_to "Artists", artists_path %></li>
          <li class="divider-vertical"></li>
          
        </ul>
        <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown" id="umenu">
            <%= link_to current_user.email, "#", :class => "dropdown-toggle", "data-toggle" => "dropdown", :href => "#umenu" %>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9">
      <%= render :partial => 'shared/flashes' %>
      <%= yield %>
    </div>
    <div class="span3">
      <div class="page-header">
        <h1><small>What is Oldtape?</small></h1>
      </div>
      Oldtape is a easy mixtape creation tool with search capabilites for songs.
    </div>
  </div>
</div>

</body>
</html>

app/views/mixtapes/_form.html.erb
<%= form_for(@mixtape) do |f| %>
    <% if @mixtape.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@mixtape.errors.count, "error") %> prohibited this mixtape from being saved:</h2>

          <ul>
            <% @mixtape.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/mixtapes/edit.html.erb
<h2><%= @mixtape.name %></h2>

<%= render 'form' %>

<%= link_to 'Show', @mixtape %> |
<%= link_to 'Back', mixtapes_path %>

app/views/mixtapes/index.html.erb
<h2>Mixtapes</h2>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @mixtapes.each do |mixtape| %>
      <tr>
        <td><%= mixtape.name %></td>
        <td><%= mixtape.description %></td>
        <td><%= link_to 'Display', mixtape, :class => 'btn btn-mini' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<p>Fix this view to display user's own mixtapes.</p>

<br/>

app/views/mixtapes/new.html.erb
<h2>New Mixtape</h2>

<%= render 'form' %>

<%= link_to 'Back', mixtapes_path %>

app/views/mixtapes/show.html.erb
<h2><%= @mixtape.name %></h2>
<p><%= @mixtape.description %></p>

<%= form_tag mixtape_path(params[:id]), :method => 'get' do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% if @songs.blank? %>
  <p>No songs found.</p>
<% else %>
<table class="table table-striped">
  <tbody>
  <% @songs.each do |song| %>
      <tr>
        <td><%= song.album.artist.name %></td>
        <td><%= song.album.name %></td>
        <td><%= song.name %></td>
        <td><%= song.duration %></td>
        <td><%= link_to 'Add', mixtapes_path, :class => 'btn btn-mini btn-action' %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th>Song</th>
    <th>Duration</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @mixtape.mixtape_songs.each do |ms| %>
  <tr>
    <td><%= ms.song.album.artist.name %></td>
    <td><%= ms.song.album.name %></td>
    <td><%= ms.song.name %></td>
    <td><%= ms.song.duration %></td>
    <td><%= link_to 'Remove', build_mixtape_path(ms), confirm: 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<br/>

app/views/shared/_flashes.html.erb
<% unless flash[:notice].blank? %>
    <div class="alert alert-info">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:notice] %>
    </div>
<% end %>
<% unless flash[:error].blank? %>
    <div class="alert alert-error">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:error] %>
    </div>
<% end %>
<% unless flash[:success].blank? %>
    <div class="alert alert-success">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:success] %>
    </div>
<% end %>
<% unless flash[:alert].blank? %>
    <div class="alert">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:alert] %>
    </div>
<% end %>

app/views/songs/_form.html.erb
<%= form_for(@song, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @song.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@song.errors.count, 'error') %> prohibited
        this song from being saved:</h2>
    <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.hidden_field :album_id, :value => params[:album_id] %>
 
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :track, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :track %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :duration, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :duration %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
    <%= link_to 'Back', album_path(params[:album_id]), :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<div class="page-header">
  <h1>New Song</h1>
</div>
 
<%= render 'form' %>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>